version: '2.15.1'

services:  
  django_gunicorn:
    volumes: 
      - static:/static
    env_file: 
      - .env
    build: 
      context: .
    ports: 
      - "8000:8000"
    # depends_on:
    #  - db

  # db:
  #   image: postgres
  #   environment: 
  #     - POSTGRES_DB=project_clean_db
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=1234
  #   ports: 
  #     - "5432:5432"
  #   restart: always

  nginx:
    build: ./nginx
    volumes: 
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
  static: