# Generated by Django 4.0.1 on 2022-01-19 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0003_location_mcprofile_citizenprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=250)),
                ('cat_value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gri_img', models.ImageField(upload_to='grievance_pics')),
                ('gri_title', models.CharField(max_length=250)),
                ('gri_desc', models.TextField(null=True)),
                ('gri_upvote', models.PositiveIntegerField(default=0)),
                ('gri_severity', models.IntegerField()),
                ('gri_priority', models.IntegerField()),
                ('gri_timeStamp', models.DateTimeField(auto_now_add=True)),
                ('gri_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grievance_data.category')),
                ('gri_location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authapp.location')),
                ('gri_uploaded_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.citizenprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=250)),
                ('status_active', models.BooleanField(default=False)),
                ('status_timeStamp', models.DateTimeField(auto_now=True)),
                ('status_grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grievance_data.grievance')),
                ('status_issuedByMC', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authapp.mcprofile')),
            ],
        ),
    ]
