# Generated by Django 4.0.1 on 2022-01-24 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_alter_mcprofile_mc_profile_img'),
        ('grievance_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='gri_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='grievance_data.category'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='gri_uploaded_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_user', to='authapp.citizenprofile'),
        ),
    ]
