# Generated by Django 4.0.1 on 2022-01-28 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_alter_mcprofile_mc_profile_img'),
        ('grievance_data', '0002_alter_grievance_gri_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_issuedByMC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authapp.mcprofile'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(choices=[('Register', 'Register'), ('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Solved', 'Solved'), ('Rejected', 'Rejected')], max_length=250),
        ),
    ]
