# Generated by Django 4.0.1 on 2022-02-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_data', '0003_alter_status_status_issuedbymc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(choices=[('Register', 'Register'), ('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Rejected', 'Rejected')], max_length=250),
        ),
    ]
