# Generated by Django 4.0.1 on 2022-03-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_data', '0006_grievance_gri_upvote_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='gri_upvote',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
