# Generated by Django 4.0.1 on 2022-03-06 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_alter_mcprofile_mc_profile_img'),
        ('grievance_data', '0008_alter_grievance_gri_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='gri_uploaded_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_user', to='authapp.citizenprofile'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='gri_upvote_list',
            field=models.ManyToManyField(blank=True, to='authapp.CitizenProfile'),
        ),
    ]
