# Generated by Django 4.0.1 on 2022-03-08 21:01

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_data', '0009_alter_grievance_gri_uploaded_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(choices=[('Garbage', 'Garbage'), ('POTHOLE', 'POTHOLE'), ('Fallen Tree', 'Fallen Tree')], max_length=250),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='gri_img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
