# Generated by Django 4.0.1 on 2022-01-19 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0003_location_mcprofile_citizenprofile'),
        ('grievance_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=250)),
                ('folder_gri_file', models.ManyToManyField(to='grievance_data.Grievance')),
            ],
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk_name', models.CharField(max_length=250)),
                ('desk_gri_files', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grievance_data.grievance')),
                ('desk_mc_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.mcprofile')),
            ],
        ),
    ]
