# Generated by Django 4.0.1 on 2022-01-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_data', '0002_alter_grievance_gri_category_and_more'),
        ('dashboard', '0002_folders_folder_desks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desk',
            name='desk_gri_files',
        ),
        migrations.AddField(
            model_name='desk',
            name='desk_gri_files',
            field=models.ManyToManyField(to='grievance_data.Grievance'),
        ),
    ]
