# Generated by Django 4.0.1 on 2022-01-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_data', '0002_alter_grievance_gri_category_and_more'),
        ('dashboard', '0003_remove_desk_desk_gri_files_desk_desk_gri_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='desk_gri_files',
            field=models.ManyToManyField(blank=True, to='grievance_data.Grievance'),
        ),
    ]
