# Generated by Django 4.0.1 on 2022-03-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_folders_folder_gri_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_detailDesc', models.TextField(null=True)),
                ('log_timeStamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
