# Generated by Django 4.0.1 on 2022-01-19 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_long', models.FloatField()),
                ('loc_lat', models.FloatField()),
                ('loc_display_name', models.TextField()),
                ('loc_suburb', models.CharField(max_length=250)),
                ('loc_town', models.CharField(max_length=250)),
                ('loc_city', models.CharField(max_length=250)),
                ('loc_municipality', models.TextField()),
                ('loc_state_distric', models.CharField(max_length=250)),
                ('loc_state', models.CharField(max_length=250)),
                ('loc_postcode', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MCProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mc_profile_img', models.ImageField(blank=True, upload_to='profiles_pics')),
                ('mc_employee_id', models.CharField(max_length=250)),
                ('mc_muncipal_co', models.TextField()),
                ('mc_location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authapp.location')),
                ('mc_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CitizenProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citi_profile_img', models.ImageField(blank=True, upload_to='profiles_pics')),
                ('citi_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
