# Generated by Django 4.0.1 on 2022-01-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_location_mcprofile_citizenprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isMcUser',
            field=models.BooleanField(default=False),
        ),
    ]
