# Generated by Django 4.0.1 on 2022-01-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_remove_location_loc_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcprofile',
            name='mc_profile_img',
            field=models.ImageField(blank=True, default='profiles_pics/default.jpg', upload_to='profiles_pics'),
        ),
    ]
